language: python
python:
  - "2.7"
before_install:
  - pip install -U setuptools
  - python bootstrap.py
  - bin/buildout
script:
  - bin/py.test -v tests/morpheme_test.py
notifications:
  emails:
    - addsict@gmail.com
  on_success: always
  on_failure: always
