application: refissue
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: django
  version: "1.3"

handlers:
- url: /
  script: refissue.main.application

builtins:
- deferred: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
