application: refissue
version: 1
runtime: python27
api_version: 1
threadsafe: true
libraries:
- name: django
  version: "1.3"

handlers:
- url: /
  script: refissue.main.application

builtins:
- deferred: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- bin/
- develop-eggs/
- eggs/
- parts/
- bootstrap.py
- buildout.cfg
- README.md
- tests

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
